groups:
- name: high_ambient_temp
  rules: 
    - alert: HighAmbientTemp
      expr: temperature_device_data_celcius > 40
      for: 5s
      labels:
        app: iot_monitoring
        severity: critical
      annotations:
        summary: "Dangerous ambient temp on {{ $labels.id }} detected: {{ $value }} C"
